image:
  file: .ybdb.Dockerfile
tasks:
  - name: ybdb
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/ybdb
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb --advertise_address=$HOST --background=true

  - name: init-services
    init: |
      docker compose -f init-voyager/compose.yml pull
    command: |
      docker compose -f init-voyager/compose.yml up

  - name: mysql
    init: |
      sudo apt-get update
      sudo apt-get install -y mysql-client
    command: |
      gp ports await 3306
      mysql -h 127.0.0.1 -P 3306 -u root -p 'Alwaysb3kind'

  - name: yb-voyager
    env:
      SECRET: Alwaysb3kind
      INSTANCE: 127.0.0.1
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/voyager-data
      wget -O ./yb-voyager https://raw.githubusercontent.com/yugabyte/yb-voyager/main/docker/yb-voyager-docker && chmod +x ./yb-voyager && sudo mv yb-voyager /usr/local/bin/yb-voyager
      gp ports await 3306

vscode:
  extensions:
    - ms-azuretools.vscode-docker

# exposed ports
ports:
  - port: 7000
    name: yb-master-web
    onOpen: ignore
  - port: 9000
    name: yb-tserver-web
    onOpen: ignore
  - port: 7100
    name: yb-master-rpc
    onOpen: ignore
  - port: 9100
    name: yb-tserver-rpc
    onOpen: ignore
  - port: 5433
    name: ysql
    onOpen: ignore
  - port: 13000
    name: ysql-api
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 12000
    name: ycql-api
    onOpen: ignore
  - port: 3306
    name: mysql
    onOpen: ignore
