image:
  file: .ybdb.Dockerfile
tasks:
  - name: ybdb
    env:
      DATA_PATH: ybdb
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/${DATA_PATH}
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/${DATA_PATH} --advertise_address=$HOST --background=true

  - name: dev-inner-loop
    init: |
      npm install -g generator-jhipster-yugabytedb
    command: |
      echo "ybdb dev inner loop workflow!"


vscode:
  extensions:
    - ms-azuretools.vscode-docker

# exposed ports
ports:
  - port: 7000
    name: yb-master-web
    onOpen: ignore
  - port: 9000
    name: yb-tserver-web
    onOpen: ignore
  - port: 7100
    name: yb-master-rpc
    onOpen: ignore
  - port: 9100
    name: yb-tserver-rpc
    onOpen: ignore
  - port: 5433
    name: ysql
    onOpen: ignore
  - port: 13000
    name: ysql-api
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 12000
    name: ycql-api
    onOpen: ignore
  - port: 8080
    name: app
    onOpen: ignore
