version: '3.9'
x-mysql-config: &mysql-env
  MYSQL_ROOT_PASSWORD: password
  # MYSQL_USER: ybvoyager
  # MYSQL_PASSWORD: password
  MYSQL_INIT_COMMAND: "--skip-grant-tables"

services:
  mysql:
    image: mysql:8.1
    restart: always
    network_mode: host
    environment:
      <<: *kong-env
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  voyager:
    image: yugabytedb/yb-voyager:1.5.1
    restart: always
    network_mode: host
volumes:
  mysql-data: