image:
  file: .ybdb.Dockerfile
tasks:
  - name: init-kafka
    env:
      CONFLUENT_HOME: ${GITPOD_REPO_ROOT}/kafka/
      KAFKA_VERSION: 7.5.0
      PATH: ${PATH}:${CONFLUENT_HOME}/bin
    init: |
      mkdir -p ${GITPOD_REPO_ROOT}/kafka/
      curl -O https://packages.confluent.io/archive/7.5/confluent-${KAFKA_VERSION}.zip
      tar -xzf confluent-${KAFKA_VERSION}.tar.gz -C ${CONFLUENT_HOME} --strip-components=1
      gp sync-done init-kafka
  - name: init-connect-hub
    env:
      CONFLUENT_HOME: ${GITPOD_REPO_ROOT}/kafka/
      PATH: ${PATH}:${CONFLUENT_HOME}/bin
      JDBC_VERSION: 10.7.4
      POSTGRES_VERSION: 2.2.1
    command: |
      gp sync-await init-kafka
      confluent-hub install --no-prompt --component-dir ${CONFLUENT_HOME}/share/confluent-hub-components confluentinc/kafka-connect-jdbc:${JDBC_VERSION}
      confluent-hub install --no-prompt --component-dir ${CONFLUENT_HOME}/share/confluent-hub-components debezium/debezium-connector-postgresql:${POSTGRES_VERSION}
      curl -o ${CONFLUENT_HOME}/share/confluent-hub-components/kafka-connect-jdbc/lib/debezium-connector-yugabytedb-1.9.5.y.33.SNAPSHOT.jar https://github.com/yugabyte/debezium-connector-yugabytedb/releases/download/v1.9.5.y.33.SNAPSHOT/debezium-connector-yugabytedb-1.9.5.y.33.SNAPSHOT.jar
      gp sync-done init-connect-hub
  - name: kafka-run
    env:
      CONFLUENT_HOME: ${GITPOD_REPO_ROOT}/kafka/
      PATH: ${PATH}:${CONFLUENT_HOME}/bin
    command: |
      gp sync-await init-connect-hub
      confluent local services start
  - name: connector-config
    env:
      CONFLUENT_HOME: ${GITPOD_REPO_ROOT}/kafka/
      PATH: ${PATH}:${CONFLUENT_HOME}/bin
    command: |
      echo "Apply connector config in this shell!"
  - name: init-postgres
    env:
      PG_VERSION: 13.3
      DATA_PATH: init-cdc
    init: |
      docker compose -f ${DATA_PATH/compose.yml pull
    command: |
      docker compose -f ${DATA_PATH/compose.yml up

  - name: ysqlsh
    env:
      DATA_PATH: init-cdc
    init: |
      gp ports await 5433 && sleep 2
      ysqlsh -f ${GITPOD_REPO_ROOT}/${DATA_PATH}/chinook.sql
    command: |
      gp ports await 5433 && sleep 2
      ysqlsh

vscode:
  extensions:
    - ms-azuretools.vscode-docker

# exposed ports
ports:
  - port: 7000
    name: yb-master-web
    onOpen: ignore
  - port: 9000
    name: yb-tserver-web
    onOpen: ignore
  - port: 7100
    name: yb-master-rpc
    onOpen: ignore
  - port: 9100
    name: yb-tserver-rpc
    onOpen: ignore
  - port: 5433
    name: ysql
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 13000
    name: ysql-api
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 12000
    name: ycql-api
    onOpen: ignore
